[project]
name = "escrow"
description = "Freelancer escrow smart contract for Stacks blockchain"
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = []
boot_contracts = []

[contracts.escrow]
path = "contracts/escrow.clar"
clarity_version = 2
epoch = "2.4"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
