[network]
name = "testnet"
node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[[network.accounts]]
# Add your testnet deployer address here
# For deployment, you'll need to configure this with your actual testnet account
